### ISSUE TITLE
internal links dont work in chrome app

### ISSUE THREAD

**Issue by yoavniran** [pioul/Minimalist-Markdown-Editor-for-Chrome#4]
first of all, love this tool. It works great. especially love the much needed side-by-side and synced scrolling.

the big thing that doesnt work for me is that internal links dont work in the preview.
For example, in one section I can put: &lt;a name="mySection"/&gt;
then in a different place in my doc i can put a link to it using: \[my section](#mySection) 

this works fine in GitHub or NPM but not in the preview pane. 

thanks,
Yoav

**Comment by pioul** [comment]
Hey, thanks for bringing this to my attention.

The technical explanation for why it didn't work is that the preview panel is placed in a sandboxed iframe, and links are handled differently within those.

So I've made sure links to both external URLs and internal URL fragments work.

You can now link to a specific part of your Markdown document using such fragments, e.g. clicking `[Chapter 2](#chapter-2)` will jump to `<h2 id="chapter-2">Chapter 2</h2>`.

However, you can only use the `id` attribute for that. I haven't bothered implementing the same behavior with `name` on anchors, since that attribute is obsolete in HTML5. If your use-case really depends on `<a name="">`, and you can't use the `id` attribute instead, please tell me, and I'll take some time to add that.

As usual with Chrome applications updates, it may take some time for you to get the latest version (usually a matter of hours). Once you do, feel free to share any feedback here.

Cheers!

**Comment by yoavniran** [comment]
works like a charm! thanks :)
